// Demo data for guest mode
export const demoProfile = {
  id: "demo-user-id",
  full_name: "Usuario Demo",
  nickname: "Demo",
  email: "demo@trado.cl",
  reputation_score: 4.8,
  total_transactions: 12,
  is_verified: true,
  verification_status: "approved",
  phone: "+56 9 1234 5678",
  address: "Santiago, Chile",
  avatar_url: null,
  created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(), // 90 days ago
  dashboard_color: "primary",
  dashboard_theme: "system",
  dashboard_background_url: null,
  bank_holder_name: null,
  bank_holder_rut: null,
  bank_name: null,
  bank_account_type: null,
  bank_account_number: null,
  rut: null,
};

export const demoWallet = {
  id: "demo-wallet-id",
  user_id: "demo-user-id",
  balance: 150000,
  blocked_balance: 25000,
  currency: "CLP",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoTransactions = [
  {
    id: "demo-tx-1",
    product_name: "iPhone 14 Pro Max",
    product_description: "iPhone 14 Pro Max 256GB, color space black, en perfecto estado.",
    amount: 850000,
    commission: 25500,
    state: "funds_secured",
    appeal_status: null,
    seller_id: "demo-user-id",
    buyer_id: "demo-buyer-1",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    invite_code: "DEMO1234",
    sale_type: "producto_envio",
    initiator_role: "seller",
    shipped_at: null,
  },
  {
    id: "demo-tx-2",
    product_name: "Diseño de Logo",
    product_description: "Diseño de logo profesional con 3 propuestas y revisiones ilimitadas.",
    amount: 75000,
    commission: 2250,
    state: "in_delivery",
    appeal_status: null,
    seller_id: "demo-user-id",
    buyer_id: "demo-buyer-2",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    invite_code: "DEMO5678",
    sale_type: "servicio",
    initiator_role: "seller",
    shipped_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-tx-3",
    product_name: "PlayStation 5",
    product_description: "PS5 edición disco, con 2 controles y 3 juegos físicos.",
    amount: 450000,
    commission: 13500,
    state: "created",
    appeal_status: null,
    seller_id: "demo-user-id",
    buyer_id: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    invite_code: "DEMO9ABC",
    sale_type: "producto_persona",
    initiator_role: "seller",
    shipped_at: null,
  },
];

export const demoMovements = [
  {
    id: "demo-mov-1",
    wallet_id: "demo-wallet-id",
    type: "deposit",
    amount: 200000,
    balance_after: 200000,
    description: "Depósito",
    status: "approved",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-mov-2",
    wallet_id: "demo-wallet-id",
    type: "escrow_release",
    amount: 48500,
    balance_after: 248500,
    description: 'Venta "MacBook Pro M2"',
    status: "approved",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-mov-3",
    wallet_id: "demo-wallet-id",
    type: "escrow_lock",
    amount: 25000,
    balance_after: 223500,
    description: 'Compra "Audífonos Sony"',
    status: "approved",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-mov-4",
    wallet_id: "demo-wallet-id",
    type: "withdrawal",
    amount: 50000,
    balance_after: 173500,
    description: "Retiro",
    status: "approved",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoBuyerProfiles: Record<string, any> = {
  "demo-buyer-1": {
    id: "demo-buyer-1",
    full_name: "María González",
    nickname: "María",
    reputation_score: 4.9,
    total_transactions: 8,
    is_verified: true,
    avatar_url: null,
  },
  "demo-buyer-2": {
    id: "demo-buyer-2",
    full_name: "Carlos Pérez",
    nickname: "Carlos",
    reputation_score: 4.5,
    total_transactions: 3,
    is_verified: false,
    avatar_url: null,
  },
};
